# Generated by Django 5.1 on 2024-08-13 18:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=99)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=99)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default='')),
                ('row_status', models.CharField(default='Current', max_length=20)),
                ('team', models.ManyToManyField(to='projectschedule.teams')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default='')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectschedule.developers')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectschedule.projects')),
            ],
        ),
        migrations.AddField(
            model_name='developers',
            name='project',
            field=models.ManyToManyField(through='projectschedule.WorkingOn', to='projectschedule.projects'),
        ),
    ]
