# Generated by Django 5.1 on 2024-08-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectschedule', '0004_alter_developers_end_date_alter_projects_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='developer_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workingon',
            name='is_relation_active',
            field=models.BooleanField(default=True),
        ),
    ]
