# Generated by Django 5.1 on 2024-08-27 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectschedule', '0005_developers_developer_active_projects_project_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingon',
            name='status',
            field=models.CharField(blank=True, default='working', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='developers',
            name='row_status',
            field=models.CharField(blank=True, default='Current', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='developers',
            name='start_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
